name: SimQA-code
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.5
  - matplotlib=3.4.2
  - black=21.7b0
  - pandas=1.3.2
  - torchtext=0.4.0
  - cudatoolkit
  - jupyter
  - jupyterlab
  - ipython
  - tqdm
  - requests
  - tensorboard=2.5.0
  - tensorboardX=2.2
  - nltk=3.6.2
  - pip:
    - antlr4-python3-runtime==4.8
    - transformers==4.9.2
    - gensim==4.0.1
    - spacy==3.1.2
    - OpenNMT-py==1.2.0
